### ISSUE TITLE
got an error Property 'getMetadata' does not exist on type 'typeof Reflect'

### ISSUE THREAD

**Issue by xavierclotet** [Gbuomprisco/typed-reducer#1]
ERROR in node_modules/typed-reducer/index.ts(62,53): error TS2339: Property 'getMetadata' does not exist on type 'typeof Reflect'.
node_modules/typed-reducer/index.ts(77,27): error TS2339: Property 'getMetadata' does not exist on type 'typeof Reflect'.
node_modules/typed-reducer/index.ts(81,13): error TS2339: Property 'defineMetadata' does not exist on type 'typeof Reflect'.

**Comment by Gbuomprisco** [comment]
Hi @xavierclotet,

sorry it's not specified, but you should probably try installing @types/reflect-metadata

**Comment by xavierclotet** [comment]
install what? typed-reducer is already installed

**Comment by Gbuomprisco** [comment]
ah sorry, the comment got cut. I meant "@ types/reflect-metadata" (remove the space - if I put it my comment gets cut again)

**Comment by xavierclotet** [comment]
thx but problem persists.

**Comment by Gbuomprisco** [comment]
Try adding it as in https://github.com/Gbuomprisco/typed-reducer/blob/master/example-app/src/tsconfig.app.json#L8

**Comment by xavierclotet** [comment]
yes now is fixed! thx!
