### ISSUE TITLE
question: aot nt working yet?

### ISSUE THREAD

**Issue by xavierclotet** [Gbuomprisco/typed-reducer#2]
I get this error when I build for production --aot:

ERROR in Error: Error encountered resolving symbol values statically. Calling function 'createReducer', function calls are not supported.

Will be supported in a near future?
The line is:
export const customerDetails = createReducer(CustomerDetailsReducer, options)(initialState);

**Comment by Gbuomprisco** [comment]
Hi @xavierclotet, I'll release a revised version that makes it AOT compliant and a way to make factories work with ngrx :+1:  (tomorrow I hope)

**Comment by Gbuomprisco** [comment]
Hi @xavierclotet,

have a look at the updated version (0.1.0), as written in the readme you can export a factory function to the StoreModule and remain AOT compliant. The only change you'll need to do is to remove the initial state from createReducer and pass it through the rootReducer instead.

https://github.com/Gbuomprisco/typed-reducer#use-with-ngrx-and-aot
